version: '3.4'

services:
    realestateagentsapi:
        image: ${DOCKER_REGISTRY-}realestateagentswebapi
        build:
            context: .
            dockerfile: src/RealEstateAgents/RealEstateAgents.WebApi/Dockerfile