version: '3.4'

services:
  realestateagents.webapi:
    image: ${DOCKER_REGISTRY-}realestateagentswebapi
    build:
      context: .
      dockerfile: RealEstateAgents/RealEstateAgents.WebApi/Dockerfile
